<?php

namespace AppBundle\Repository;

/**
 * AppMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
