<?php

namespace AppBundle\Repository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTimestampRange($user, $from, $to)
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.user = :user')
            ->andWhere('t.timestamp >= :from')
            ->andWhere('t.timestamp <= :to')
            ->setParameter(':user', $user)
            ->setParameter(':from', $from)
            ->setParameter(':to', $to)
            ->addOrderBy('t.timestamp')
            ->getQuery()->getResult();
    }
}
