<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    /* private $em;

    public function __construct(EntityManager $em) {
        $this->entityManager = $em;
    } */

    public function addFeedback($map)
    {
        $query = $this->createQueryBuilder('t')
            ->insert('feedback')
            ->setValue('message', '?')
            ->setParameter(0, 'asd')
            ->getQuery();
        $result = $query->execute();
    }
}
