<?php

namespace AppBundle\Repository;

/**
 * PushTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PushTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
