<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;

/**
 * SumTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SumTrainingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDummy($list, $user) { // Doctrine\ORM\Query::HYDRATE_OBJECT
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.sessionId in (:list)')
            ->andWhere('t.userId = :user')
            ->setParameter(':list', $list)
            ->setParameter(':user', $user);

        return $qb->getQuery()->getResult(); // $hydrate
    }
    public function findBySessionIdsAndUser($list, $user) {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.sessionId in (:list)')
            ->andWhere('t.userId = :user')
            ->setParameter(':list', $list)
            ->setParameter(':user', $user);

        return $qb->getQuery()->getResult();
    }
    public function findBySessionIdRange($from, $to, $user, $hydrate = Query::HYDRATE_OBJECT)
    {
        $qb = $this->createQueryBuilder('t')
            // ->distinct()
            ->select('t')
            ->where('t.sessionId >= :from')
            ->andWhere('t.sessionId <= :to')
            ->andWhere('t.userId = :user')
            ->setParameter(':from', $from)
            ->setParameter(':to', $to)
            ->setParameter(':user', $user)
            ->addOrderBy('t.sessionId');

        return $qb->getQuery()->getResult($hydrate);
    }
    public function findTrainingDaysByUser($user)
    {
        $qb = $this->createQueryBuilder('t')
            ->distinct()
            ->select('t.sessionId')
            ->andWhere('t.userId = :user')
            ->setParameter(':user', $user)
            ->addOrderBy('t.sessionId');

        return $qb->getQuery()->getResult();
    }
}
