imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    jms_serializer.serialized_name_annotation_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../tmp/"
    fragments:       ~
    http_method_override: true
    assets: 
        packages:
            views_css:
                base_path: css/views/

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# RMS push
rms_push_notifications:
  android:
      gcm:
          api_key: "%android_gcm_api_key%"
          use_multi_curl: true
          dry_run: "%android_gcm_dry_run%"
  ios:
      sandbox: "%ios_push_dry_run%"
      pem: "%ios_push_path_to_pem%"
      passphrase: "%ios_push_passphrase%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationFormType
    profile:
        form:
            type: AppBundle\Form\ProfileFormType

jms_serializer:
#    enable_short_alias: false
    metadata:
        auto_detection: true
        directories:
            FOSUserBundleö:
                namespace_prefix: FOS\UserBundle
                path: '@AppBundle/Resources/config/serializer/fos'
hwi_oauth:
    firewall_names: ['main']
    fosub:
        properties:
            facebook: facebook_id
            google:   google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%facebook.client_id%'
            client_secret:       '%facebook.client_secret%'
            scope:               "email, public_profile"
            paths:
                email: email
            options:
                display: page
        google:
            type:   google
            client_id:           '%google.client_id%'
            client_secret:       '%google.client_secret%'
            scope:               "email profile"
            options:
                access_type:     offline
            options:
                display: page

gesdinet_jwt_refresh_token:
    user_provider: fos_user.user_provider.username
    ttl_update: true
