# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.prefilter.json_request_transformer:
        class: AppBundle\Listeners\JsonRequestTransformerListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.security.jwt_token_authenticator:
        class: AppBundle\Security\JWTAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
        class: AppBundle\Listeners\HashPasswordListener
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.api.exception_listener:
        class: AppBundle\Listeners\ApiExceptionListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.training.service:
        class: AppBundle\Services\TrainingService
        autowire: true
    app.avg.training.service:
        class: AppBundle\Services\AvgTrainingService
        autowire: true
    app.user.service:
        class: AppBundle\Services\UserService
        autowire: true
    app.plan.service:
        class: AppBundle\Services\PlanService
        autowire: true
    app.plan_training.service:
        class: AppBundle\Services\PlanTrainingService
        autowire: true
    app.event.service:
        class: AppBundle\Services\EventService
        autowire: true

    app.provider.oauth:
        class: AppBundle\Security\Provider\OAuthUserProvider
        arguments: ["@session",'@fos_user.user_manager',{facebook: facebookId, google: googleId}]
    app.oauthfailurehandler:
        class: AppBundle\Handlers\OAuthFailureHandler
#        arguments: ["@security.http_utils", {}, "@service_container"]
        autowire: true
    app.form.registration:
        class: AppBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_bundle_registration_form_type }
    app.form.profile:
        class: AppBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_bundle_profile_form_type }

    app.security.authentication.handler.authentication_success:
        class: AppBundle\Security\AuthenticationSuccessHandler
        arguments: ["@lexik_jwt_authentication.jwt_manager", "@event_dispatcher", "@app.user.service"]
        tags:
            - { name: monolog.logger, channel: security}
