AppBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: fos_user.username.blank
                groups:
                    - Registration
                    - Profile
            - Length:
                min: 2
                minMessage: fos_user.username.short
                max: 255
                maxMessage: fos_user.username.long
                groups:
                    - Registration
                    - Profile
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups:
                    - Registration
                    - Profile
            - Email:
                message: fos_user.email.invalid
                groups:
                    - Registration
                    - Profile
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 254
                maxMessage: fos_user.email.long
                groups:
                    - Registration
                    - Profile
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups:
                    - Registration
                    - Profile
            - Length:
                min: 2
                minMessage: fos_user.password.short
                max: 4096
                groups:
                    - Registration
                    - Profile
        bodyWeight:
            - NotBlank:
                groups:
                    - Registration
                    - Profile
            - Range:
                min: 30
                max: 500
                groups:
                    - Registration
                    - Profile
        firstName:
            - Length:
                min: 0
                max: 255
                groups:
                    - Registration
                    - Profile
        lastName:
            - Length:
                min: 0
                max: 255
                groups:
                    - Registration
                    - Profile
        gender:
            - NotBlank:
                groups:
                    - Registration
                    - Profile
            - Choice: { callback: getGenders }
        club:
            - Length:
                min: 0
                max: 255
                groups:
                    - Registration
                    - Profile
        artOfPaddling:
            - NotBlank:
                groups:
                    - Registration
                    - Profile
            - Length:
                min: 1
                max: 255
                groups:
                    - Registration
                    - Profile